SELECT * FROM customers;

-- Total revenue generated by male vs. female customers

SELECT 
	SUM(CASE WHEN gender = 'Male' THEN purchase_amount END) AS revenue_by_males,
	SUM(CASE WHEN gender = 'Female' THEN purchase_amount END) AS revenue_by_females
FROM customers;

SELECT 
	SUM(purchase_amount) FILTER(WHERE gender = 'Female') AS revenue_by_females,
	SUM(purchase_amount) FILTER(WHERE gender = 'Male') AS revenue_by_males
FROM customers;

SELECT
	gender,
	SUM(purchase_amount) AS purchase_amount
FROM customers
GROUP BY gender;

-- Customers used a discount but still spent more than the average purchase amount

SELECT AVG(purchase_amount) FROM customers;

SELECT *
FROM customers
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customers);

-- The categories with the highest average review rating

SELECT
	category,
	AVG(review_rating)::NUMERIC(10,2) AS average_review_rating
FROM customers
GROUP BY category
ORDER BY average_review_rating DESC
LIMIT 5;

-- The top 5 products with the highest average review rating

SELECT
	item_purchased,
	AVG(review_rating)::NUMERIC(10,2) AS average_review_rating
FROM customers
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

-- Average purchase amounts between standard and express shipping

SELECT
	(AVG(purchase_amount) FILTER(WHERE shipping_type = 'Standard'))::NUMERIC(10,2) AS average_purchase_standard,
	(AVG(purchase_amount) FILTER(WHERE shipping_type = 'Express'))::NUMERIC(10,2) AS average_purchase_express
FROM customers;

SELECT 
	shipping_type,
	AVG(purchase_amount)::NUMERIC(10,2) AS average_purchase_amount
FROM customers
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

-- Average spend and total revenue between subscribers and non-subscribers

SELECT 
	subscription_status,
	COUNT(customer_id) AS status_count,
	AVG(purchase_amount)::NUMERIC(10,2) AS average_spend,
	SUM(purchase_amount)::NUMERIC(10,2) AS total_spend
FROM customers
GROUP BY subscription_status;

-- Each product's percentage share of all discounted purchases

SELECT
	item_purchased AS products,
	((COUNT(item_purchased) / SUM(COUNT(item_purchased)) OVER()) * 100)::NUMERIC(10,2) AS purchase_percentage
FROM customers
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY purchase_percentage DESC
LIMIT 5;

-- Top 5 products with the highest percentage of purchases with discounts applied

SELECT
 	item_purchased AS purchased_products,
 	ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(item_purchased), 2) AS discounted_purchases
FROM customers
GROUP BY item_purchased
ORDER BY discounted_purchases DESC
LIMIT 5;

-- Segment customers into New, Returning and Loyal based on their total number of previous purchases the show the count of each segment


